### ISSUE TITLE
[Login] Forgot password: Email for password reset not received

### ISSUE THREAD

**Issue by cristinamhm** [code4romania/vic#213]
### Description

-->I am not receiving the password reset email despite requesting it.

### Test environment
Platform: mobile app
OS: iOS

### Preconditions

I have an existing user account.
I have forgotten your password and initiated the password reset process.
I have provided a valid email address associated with your user account during the password reset request.

### Test Data

- you can use any valid account 

### Steps of Reproduction

Visit the login page of TEO. 
Click on the "log in" .
Press on "Forgot your password?" 
Enter your registered email address.
Click the "Send reset code" button 
Check your email inbox for the password reset email.
Confirm that the email is not received within a reasonable timeframe (e.g., 5-10 minutes).

**Comment by radulescuandrew** [comment]
@mirunaioana-msc Please close as inactive.

**Comment by radulescuandrew** [comment]
Closed as inactive and not reproducible.
