### ISSUE TITLE
Unnecessary 'Open with Teo?' prompt appears during app redirects

### ISSUE THREAD

**Issue by cristinamhm** [code4romania/vic#215]
### Description

While using the app, I have noticed that an unnecessary and disruptive prompt appears when attempting to make a redirect to the app. This prompt asks, "Open with Teo?" when it should not be triggered, as it interrupts the expected behavior of a smooth redirect.

### Test environment
Platform: mobile app
OS: iOS

### Preconditions

You have the app installed and logged in.

### Test Data

- any account

### Steps of Reproduction

Launch the app and log in.
Navigate to a section that initiates a redirect. ( for example, try login with Apple / Google account ) 
As you initiate the redirect, observe the screen for an unwanted prompt that asks, "Open with Teo?"

### Expected Result

When initiating a redirect to the app, the expected behavior is that it should occur seamlessly, without any unnecessary prompts or interruptions.

### Actual Result

The issue is that an unwanted "Open with Teo?" prompt appears during the redirect process, which disrupts the expected user experience.

See attachment
![IMG_2880](https://github.com/code4romania/teo/assets/49166972/c8313fc1-cbad-4213-a01c-60ff7fc9a35c)

**Comment by anastk-code4** [comment]
*Note: 
I also tested this. it does not occur when using Android device

**Comment by mirunaioana-msc** [comment]
cannot reproduce anymore, seems to be fixed (tested on both iOS and Android)
