### ISSUE TITLE
[Join NGO] Receive join request answer: Org update tile is not displayed on Home page

### ISSUE THREAD

**Issue by monikozi** [code4romania/vic#216]
### Description

Mobile [Receive join request answer] - Org update tile is not displayed on Home

### Test environment

Android

### Preconditions

As a Volunteer I make my first join request

### Test Data

New Volunteer with no organisation

### Steps of Reproduction

As Volunteer in Mobile:
Search for an Org
Add a request to join an org

As NGO admin in Web - reject the request with or without message

### Expected Result

Expected result:  According to figma, the volunteer should see a notification in the app about the rejected request

### Actual Result

Actual result: The update in organisations tile is not displayed in the app

### Notes (optional)

However, the volunteer gets an email notification. 

### Screenshots (optional)

![Screenshot_20230927_190530_teo](https://github.com/code4romania/teo/assets/64305252/c0ea25a4-2571-4904-b474-fd143d026de2)

![2023-09-27_18h57_09](https://github.com/code4romania/teo/assets/64305252/2063d8ce-0a09-440d-afcb-42a35c3ffc28)

![Screenshot_20230927_191114_teo](https://github.com/code4romania/teo/assets/64305252/d2884b73-7e34-4008-8ab4-17a17f89595e)

**Comment by andrei-manda** [comment]
Steps to Reproduce:
1. [MOBILE] Initiate a requested to join an NGO
2. [WEB] Reject the request
3. [MOBILE] Navigate to the Homepage

Expected Result:
3. A [notification](https://www.figma.com/design/fBxQarllPrE9kEt22bIBa1/VIC-(Management-de-voluntari)-%2F-ex.-TEO?node-id=10472-91982&t=UujnKG5qIgZIhbdF-4) appears, informing the user about the rejection and by clicking it redirects user to the "[Request Rejected](https://www.figma.com/design/fBxQarllPrE9kEt22bIBa1/VIC-(Management-de-voluntari)-%2F-ex.-TEO?node-id=10472-91928&t=UujnKG5qIgZIhbdF-4)" page

Actual Result:
3. No notification is displayed

Note:
For the new accounts, only email notifications are sent by default. The user has to access the notifications settings and select the 'Push Notification' option

**Comment by radulescuandrew** [comment]
@andrei-manda @mirunaioana-msc Here will handle the `tiles` problem. This was not part of the initial BRs, it was only intended to be received as Push Notification. Please remove the `bug` tag.

**Comment by andrei-manda** [comment]
This fix is not part of the current deployment.
