### ISSUE TITLE
Start/end dates inconsistency

### ISSUE THREAD

**Issue by danut3101** [code4romania/vic#217]
### Description

On creating events, the end date/time should not be earlier to the start date/time

### Preconditions

The user in on Add new event

### Test Data
.

### Steps of Reproduction
1. Select events from left menu
2. Click "+Add event" button
3. In Start Date box put 21.09.2023, 18:45
4. In End Date box put 07.09.2023, 18:30
5. Fill all other required data .
6. Save or Publish

### Expected Result

An error message to be display during de validation stage, and disable the save ability
or 
A message to be display immediately after fill the wrong date

### Actual Result

Save Ok without any problem

### Notes (optional)

.

### Screenshots (optional)
![image](https://github.com/code4romania/teo/assets/7722662/ff00a5e2-9c72-4bb0-960c-da0630668cc0)

**Comment by andrei-manda** [comment]
Closed -> the issue has been solved.

![image](https://github.com/user-attachments/assets/6141c964-d012-4a7b-916c-421c8e603ebb)
