### ISSUE TITLE
[Registration] Incorrect 'Email or Phone Number Already Used' error message for invalid phone number and unused email

### ISSUE THREAD

**Issue by cristinamhm** [code4romania/vic#218]
### Description

When attempting to create an account ( with apple id ), I encountered an issue where I received an error message stating, "Email or phone number already used," even though my phone number was invalid and my email address had not been used previously. This error message is misleading and does not accurately reflect the actual issue.

### Preconditions

You are reaching the registration page.
You are providing a valid, unused email address. 
You are entering an invalid phone number (not previously used for registration).

### Test Data

- any apple id 
- phone number: +40000000000

### Steps of Reproduction

Reach the registration page of the application.
Choose the apple id registration option.
Enter an invalid phone number ( +40000000000 )
Complete the other required fields.
Attempt to submit the registration form.

### Expected Result

When entering a valid email address and an invalid phone number, the expected behavior is to receive an error message related to the invalid phone number, rather than a message suggesting that the email or phone number is already in use.

### Actual Result

The issue is that the error message "Email or phone number already used" is displayed, even though the phone number is invalid and the email address has not been used before.

[](
![IMG_2881](https://github.com/code4romania/teo/assets/49166972/3cc905c3-c153-425e-af6c-a4e12acb3623)
url)

**Comment by andrei-manda** [comment]
Bug closed -> phone number input only validates the number of characters: 9 or 10 digits; If 9 digits are entered, a 0 is automatically added in front. 

However, the format is not validated, so the number was already used.
