### ISSUE TITLE
[Registration] Account mandatory details are not validated for duplicates on first introducing them

### ISSUE THREAD

**Issue by monikozi** [code4romania/vic#225]
### Description

Mobile [Create Volunteer account] - Account mandatory details are not validated for duplicates on first introducing them

### Test environment

Android

### Preconditions

As a Volunteer with no account > access TEO using the Sign in with Google option > proceed to app with the mandatory data
Log out

### Test Data

n/a

### Steps of Reproduction

As a Volunteer > 
create TEO account with Email or phone > 
Create account using the same email and phone information as those in the precondition, set password > 
Continua > 
proceed to next screen Date Cont

### Expected Result

Expected result: The unique email validation to be done on the Create account step, not in Date Cont

### Actual Result

Actual result: The email or phone number validation is done on the Date Cont page

### Notes (optional)

n/a

### Screenshots (optional)

![Screenshot_20230927_200050_teo](https://github.com/code4romania/teo/assets/64305252/3f3c02f9-dce6-44bb-84c8-7bb987064332)

**Comment by andrei-manda** [comment]
Closed -> duplicated by https://github.com/code4romania/vic/issues/232
