### ISSUE TITLE
[Events] Error not showing full message when volunteer profile is not completed

### ISSUE THREAD

**Issue by danut3101** [code4romania/vic#226]
### Description

When I try to join an event > save the RSPV, an vague error message appear telling "Please fill the profile..." but the display size do not allow to display entire message. Anyway, the volunteer profile was full filled.

### Preconditions

User looged on mobile with Google accont with the required data filled (identity, name, contact)

Android device

### Test Data

.

### Steps of Reproduction

1. login in mobile application (or create a new account)
2. Select the desired organization
3. in the events tabs select an event to participate
4. (if required) fill the optional mention
5. Click on save.

### Expected Result

An confirmation success message and the subscription to be saved

### Actual Result
An error incomplete message  "Va rugam sa completati profilul de v."

**Comment by anastk-code4** [comment]
enhancement: 
it would be ideal, in this case, to show the full error message and a button that leads the user to the 'Voluntar' page (with the relevant workspace selected)

**Comment by radulescuandrew** [comment]
@andrei-manda Please check and close when the related one is done.

**Comment by luciatugui** [comment]
Fixed in staging, will soon arrive in production. 🏎️
