### ISSUE TITLE
Invalid identification number (mobile)

### ISSUE THREAD

**Issue by danut3101** [code4romania/vic#229]
### Description

When set or edit volunteer identification data, if is filled as ID number an existing number appear an error message about "Invalid identification number". The problem is the verification is done only by ID number section not on the pair ID Serial/ID Number

### Preconditions

.

### Test Data

.

### Steps of Reproduction

1. Log in android application as volunteer  (or create a new account)
2. On the Identification section fill in ID serial box any Pair of letters
3. On the Identification section fill in ID number box "123456"
4. Fill other required data
5. Click on submit button

### Expected Result

Save the data

### Actual Result

An error message  "Invalid identification number" appear

**Comment by andrei-manda** [comment]
Closed -> the issue has been fixed.
