### ISSUE TITLE
[Volunteer] Sign in with Google - the google account selection browser tab remains open

### ISSUE THREAD

**Issue by monikozi** [code4romania/vic#231]
### Description

Mobile [Volunteer Login] Sign in with Google - the google account selection browser tab remains open

### Test environment

Android

### Preconditions

The Volunteer to have a google account

### Test Data

n/a

### Steps of Reproduction

As a Volunteer, log in using the **Sign in with Google**
An account selection tab opens in the browser
Select the desired account
The app refreshes to display shortly the Login scree and then it launches the Home page
Log out

Repeat the previous series of steps

Observe the browser: two tabs with Google account selection are still open in the browser and still loading

Close all apps

Repeat the **Sign in with Google** steps again

Observe the browser 

### Expected Result

Expected result: the Google account selection tabs to be closed once the loading is finished. 

### Actual Result

Three tabs with Google account selection are open in the browser and still loading

### Notes (optional)

The error at 00:44 only occurs when the screen recorder is running. Please have a look if the error has any relevance. 

### Screenshots (optional)

https://github.com/code4romania/teo/assets/64305252/86ba9c52-f9f6-485c-b05f-3d92c6589fce

**Comment by andrei-manda** [comment]
This is an invalid issue as we currently no longer use the social platforms to register.
