### ISSUE TITLE
[Events] Event time are different in the mobile app compared to the web app

### ISSUE THREAD

**Issue by BirtasAdrian** [code4romania/vic#234]
### Description
The time in the web app and mobile app are different for events

### Preconditions

1. To have the mobile app installed and logged in as a volunteer.
2. To be a volunteer in an organization
3. An event created in organization

### Steps of Reproduction

1. Go to "Evenimente" in mobile app
2. Tap on "Evenimente" section
3. Go to the header and tap on "Ale organizatiei mele"
4. Select an event
5. Go to https://teo-development.onghub.ro/events
6. Select the same event 
7. Look at the time displayed

### Expected Result

The time should be the same in mobile app and web app for an event 

### Actual Result

The time is not the same in mobile app and web app for an event 

### Screenshots (optional)

Note: 16:15-17:15 in the mobile app and in the web app is 19:15-20:15

![Hour in the mobile app for the event](https://github.com/code4romania/teo/assets/90641668/19f33b6d-ead6-472a-aebe-7f7bb4c62381)

Web screenshot

![image](https://github.com/code4romania/teo/assets/90641668/f5a071aa-5aad-4c64-890a-10f9ce10825a)

**Comment by radulescuandrew** [comment]
@birloiflorian Done. Please deploy in internal testing and testflight
