### ISSUE TITLE
[NGO profile] NGO profile details changes done in ONGHub do not reflect in TEO mobile/web app

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/vic#241]
### Description

As a AdminONG user, I edited my NGO's information (such as name, description, contact email etc) from ONGHub > Profil organizatie > Date generale, and saved the changes. 
The changes are not visible in TEO.

*However, when I edit the NGO description in TEO web app with a personalised one, the changes are visible in the TEO mobile app.

### Test environment

Web and mobile

### Preconditions

_no need_

### Test Data

_no need_

### Steps of Reproduction

1. Login on https://app-staging.onghub.ro/ as an AdminONG (with access to TEO app)
2. Go to My NGO profile > General data (Organizatia mea > Date generale) 
3. Edit information (NGO name, contact email, NGO descriptions etc) and save changes
4. Login on TEO web app with the same user
5. Go to 'Structura ONG' 
6. See information is not updated
7. Go to TEO mobile app and login with any user
8. Find this NGO profile page (from NGO list)
9. Open and see information is not updated

### Expected Result

Profile information changes in ONGHub are reflected in TEO mobile/webapp

### Actual Result

See the updates in TEO apps at refresh. 

### Screenshots (optional)
ONGHub details
<img width="1440" alt="image" src="https://github.com/code4romania/teo/assets/95479576/49b0066b-bd62-4d8e-9be0-b33a1f9f1b7f">

TEO web details
<img width="1440" alt="image" src="https://github.com/code4romania/teo/assets/95479576/f61b4d0a-d57b-47c4-accb-d3004cf14fc6">

TEO mobile details
![image](https://github.com/code4romania/teo/assets/95479576/33c22b9a-a639-4d9e-9cc7-745c000e2be2)

**Comment by birloiflorian** [comment]
JOB for sync.

**Comment by andrei-manda** [comment]
Closed -> a sync button was added to the 'Structura ONG' page to pull the respective data from the NGO Hub.
