### ISSUE TITLE
[NGO profile] NGO description reset doesn't work

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/vic#242]
### Description
As an AdminONG in the TEO web app, I edited the pre-filled (pulled from ONGHub) description to a personalised one and saved  the changes. Then, I edited the description again - this time I deleted all text inputed and saved changes. I received a notification saying "Descrierea organizatiei a fost actualizata", but the changes were not made - the description is still the last one inputted, and not reseted to default. 

### Test environment
Web

### Preconditions
Have AdminONG user. Have access to TEO. 

### Test Data
_not neccessary_

### Steps of Reproduction

1. Login as AdminONG in ONGHUB, access TEO web app.
2. Go to NGO profile in TEO web app
3. Click on 'Edit' button to edit the description
4. See description field is pre-filled with NGO description from ONGHub (ONGHub > Organizatia mea > Date Generale > Descriere) 
5. Input any new text (make sure you save a personalised description and not the default one)
6. Save changes, see changes were made
7. Click again on 'Edit' button
8. Remove all text from the field
9. Save changes
10. See notification "changes have been made", but the description text is the previous one inserted

### Expected Result
NGO description is reset to its default value (the one prefilled from ONGHub)

### Actual Result
NGO description is the last one successfully saved, before removing all text.

### Screenshots (optional)
<img width="1440" alt="image" src="https://github.com/code4romania/teo/assets/95479576/ebab28b5-752e-4b1c-8c1c-af5e56b1708d">

**Comment by radulescuandrew** [comment]
Additional validation was added to prevent erasing the text without error. As discussed w @overeha, if someone wants to reset, will just copy paste from ONGHub. The "reset" method can be easily implemented in the future as we already have it when creating the account. 

Close for now.
