### ISSUE TITLE
(CRITICAL) Contracts generation does not pull volunteer list nor template list 

### ISSUE THREAD

**Issue by overeha** [code4romania/vic#268]
If I want to generate volunteering contracts I do not see the volunteers nor the template I uploaded in the dropdowns. This is a critical bug. 

![Screenshot 2024-02-27 at 12 39 01](https://github.com/code4romania/vic/assets/45068169/06693ed3-6920-4665-974f-711363aeee26)

**Comment by radulescuandrew** [comment]
@birloiflorian 2 options:
1. change the text from "No options" to "Start typing to search..." 
2. Load 10-15 items + load more

**Comment by andrei-manda** [comment]
The text has been changed but the items are not pre-loaded yet.

**Comment by radulescuandrew** [comment]
@andrei-manda There were 2 mutual exclusive options from which the 1st was chosen and communicated to Olivia. 
This issue should have been closed already, but we can keep it around to **load items in all selects to improve the bad UX**

**Comment by luciatugui** [comment]
Now the 2nd option is implemented as well, we will load ~10 items and load more as we scroll. This happens where we select volunteers, events, cities and admins. For the activity and templates, we now load all of the options at once.
