### ISSUE TITLE
Volunteering hours set on a date appear on the following one

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/vic#269]
### Description

When a volunteer declares a set of volunteering hours for approval, the hours appear fine on the volunteer's app, but they appear as being one day later. 
They appear fine on the volunteer's app, at entry, and after approval, but not in the admin panel.

### Test environment

The error reproduces on web, but the test data comes from mobile.

### Steps of Reproduction

1. Open the mobile app as a volunteer registered in an organization
2. Go to `Voluntar > Ore de voluntariat`
3. Add a new entry of volunteering time with the date **15.02.2024**
4. Go to the admin of the organization above
5. Go to `Ore de voluntariat > Solicitări de aprobar`
6. Look at the `Data efectuării`

### Expected Result

The date that appears in the admin should be **15.02.2024**

### Actual Result

The date that appears in the admin is **_16_.02.2024**

### Notes (optional)

Some organizations need to have the correct numbers here since they use this feature extensively.

### Screenshots (optional)

Data entered into the app
<img width="421" alt="data entered into the app" src="https://github.com/code4romania/vic/assets/2820084/1aeba8d6-9c3e-4c8c-897a-1ccb0c43af2b">

Data appearing in the admin
<img width="421" alt="data appearing in the admin" src="https://github.com/code4romania/vic/assets/2820084/dcedb7a6-7664-4954-a51e-9b6cef6a6cf4">

**Comment by radulescuandrew** [comment]
Done. Ready for deploy
