### ISSUE TITLE
The list of volunteers doesn't get downloaded

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/vic#270]
### Description

An admin of an NGO can't download the list of volunteers.

### Test environment

On Web, in the NGO's admin interface.

### Steps of Reproduction

1. Log into the admin interface as an NGO admin
2. Go to `/volunteers`
3. Click on `Descarcă tabel`

### Expected Result

The list of volunteers is generated and downloaded.

### Actual Result

Nothing happens

**Comment by andrei-manda** [comment]
Now it works -> task closed
