### ISSUE TITLE
[Admin] Can't clear optional fields for new activity categories

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/vic#272]
### Description

When creating a new activity category, you can't you can't leave a selector with no items once you've selected something even though the fields are optional.

### Test environment

Web, in the admin, at the path: `/activity-types/add`

### Steps of Reproduction

Example:
1. Go to `/activity-types/add`
2. Select an option for any of the following fields: `Image`, `Branch`, `Department`, or `Role`
3. Try to clear the selection

### Expected Result

There should be a way to clear the current selection.

### Actual Result

Once an item has been selected, you need to have an item selected for that category or refresh the page to clear the information

### Notes (optional)

The `Image` field isn't marked as mandatory but it seems like it should be, since the category needs to have an image.

### Screenshots (optional)
![Screenshot 2024-03-01 at 12 19 48](https://github.com/code4romania/vic/assets/2820084/84fd282e-05ca-4681-a24d-4403d9695220)

**Comment by MarG66** [comment]
@dragos1195 Testing failed - Unable to add or edit category without selecting branch, department and role. These fields are optional.

**Comment by luciatugui** [comment]
This task is prepared to be tested again. 
Now, deselecting an option is possible by re-clicking on it. If deselection is allowed, you'll see an 'x' icon indicating that:
<img width="514" alt="after" src="https://github.com/user-attachments/assets/9a746632-d69f-4580-94b4-269eaa27156d">
