### ISSUE TITLE
[Join NGO] New user can't join an organization, either directly or by access code

### ISSUE THREAD

**Issue by Maria-Leustean** [code4romania/vic#277]
**Description**

On the mobile app, when accessing the profile of an NGO, the "Alătură-te organizației” button and the „Ai cod de acces” link are unresponsive, and produce no results when clicked by an user whose data is not fully completed. 

**Test environment**

On Mobile, using Android

**Preconditions**

The user has an account on the Vic mobile platform, and is logged in. The user has not been signed up as a volunteer of the NGO before (as if they have, the "Reintră în organizație" button appears instead, which works). The user ID data is not yet completed.

**Steps of Reproduction**

1. Log into the mobile application.
2. In the "Caută" tab of the app, look for the relevant NGO (for example, has been attempted for Asociatia Code for Romania) and access its profile by clicking on it.
3. At the bottom of the screen, click on the "Alătură-te organizației” button/ the „Ai cod de acces” link bellow it.

**Expected Result**

If the user clicked on the "Alătură-te organizației” button, a volunteer request is sent to the NGO or, if their data is not fully completed, an error message mentioning this appears. 
If the user clicked on the „Ai cod de acces” link, they are redirected to a page where they can introduce the code or, if their data is not fully completed, an error message mentioning this appears.  

**Actual Result**

Nothing happens when either the button or the link are clicked.

**Comment by tudoramariei** [comment]
I think a bigger issue in the app might cause this.
When trying to do any action in the NGO without having a completed profile, you get an error, but the error appears behind the overlay you're on, making it almost invisible.

**Comment by Maria-Leustean** [comment]
> I think a bigger issue in the app might cause this. When trying to do any action in the NGO without having a completed profile, you get an error, but the error appears behind the overlay you're on, making it almost invisible.

About this, I think this might be true - I have since tested the button with someone who had all the data completed and it worked. So it seems unresponsive only for those who did not have the data completed - they did not seem to receive/see an error message either.

**Comment by tudoramariei** [comment]
I saw I was getting a clear warning when trying to join an organization.
But the error reproduces when trying to log hours as a volunteer.

**Comment by Maria-Leustean** [comment]
I will try it out again tomorrow as well, with someone who hasn't filled the data yet, to see if the problem reappears or it only happened that once.

**Comment by Maria-Leustean** [comment]
We can delete this issue, as discussed during the call.
