### ISSUE TITLE
[Events] Users who have previously exited an organization, cannot choose to participate to open public events of that NGO (without re-joining)

### ISSUE THREAD

**Issue by Maria-Leustean** [code4romania/vic#278]
**Description**

On the mobile app, if an user who has previously left an organization tries to join one of its open public events (without rejoining the organization manually beforehand), they receive an error message: "Profilul de voluntar nu este activ".

**Test environment**

On Mobile, using Android

**Preconditions**

The user has an account on the Vic mobile platform, and is logged in. All necessary data has been completed beforehand in the user profile (account data and ID data). The user has been signed up as a volunteer of the NGO before, but has previously chosen to exit the organization and is currently not one of its volunteers. 

**Steps of Reproduction**

1. Log into the mobile application.
2. In the "Caută" tab of the app, look for the relevant NGO (for example, has been attempted for Asociatia Code for Romania) and access its profile by clicking on it.
3. Scroll to "Evenimente deschise" and click on the wished event (for example, Tech research).
4. Click on the "Particip" button at the bottom of the screen.

**Expected Result**

The user is signed up to the event.

**Actual Result**

The user is unable to join the event and an error message appears at the top of the screen: "Profilul de voluntar nu este activ".

**Notes (optional)**

The problem only exists if the user tries to join the event directly, without signing up again as a volunteer to the whole organization (through the "Reintră în organizație" button on the NGO profile). If they first rejoin the organization and then try to join the event, the problem disappears. 

**Screenshots (optional)**
Attached bellow, in order
![1](https://github.com/code4romania/vic/assets/139780470/62c75c59-5b9e-4805-9a89-4f4ccb296e64)
![2](https://github.com/code4romania/vic/assets/139780470/10fcd8a7-7ed5-439f-a879-c53e2309f497)
![3](https://github.com/code4romania/vic/assets/139780470/401191f8-dd19-493d-9cda-c738fa352b35)

**Comment by andrei-manda** [comment]
bug fixed.
