### ISSUE TITLE
[Events] Open public events that the user has opted to join do not appear in the "Particip" tab 

### ISSUE THREAD

**Issue by Maria-Leustean** [code4romania/vic#283]
**Description**

On the mobile app, when accessing the "Evenimente" tab, the user cannot see open public events they have opted to participate to in the "Particip" section.

**Test environment**

On Mobile, using the Android staging app

**Preconditions**

The user has an account on the Vic mobile platform, and is logged in. The user has chosen to participate to one or more open public events, by clicking on the "Particip" button on the page of the event. 

**Steps of Reproduction**

1. Log into the mobile application.
2. Opt to participate to one or more events: access the Event page either from the "Deschise" section of the "Evenimente" tab or from the NGO profile; then click on the "Particip" button.
3. After signing up to the event, go to the "Evenimente" tab. Check if it appears in the "Particip" section.

**Expected Result**

The user can see all events they participate to in the "Particip" section of the "Evenimente" tab.

**Actual Result**

The "Particip" section of the "Evenimente" tab remains empty, despite the user having joined an event. 

**Notes (optional)**

This test was carried out for an user who is not yet part of the/an NGO.

**Screenshots (optional)**
The event the user joined:
![Screenshot_20240329_111304_vic](https://github.com/code4romania/vic/assets/139780470/6a20cfdb-aec1-46ff-a83c-494e21792141)

The "Particip" section of the "Evenimente" tab after having joined the event:
![Screenshot_20240329_111315_vic](https://github.com/code4romania/vic/assets/139780470/159f2f64-4047-429e-8d7c-82e891041d1b)

**Comment by andrei-manda** [comment]
As the note says - this behavior occurs for users that are not a part of the respective NGO.

**Comment by andrei-manda** [comment]
@birloiflorian for public events, volunteers should not be required to complete the _Volunteer Profile_, regardless of their status with the respective NGO.

**Comment by birloiflorian** [comment]
@andrei-manda now the ACTIVE or ARCHIVED volunteers should be able to join events regardless if they have a volunteer profile or not.
