### ISSUE TITLE
[Registration] When inputted data was already used, error message is shown too late

### ISSUE THREAD

**Issue by anastk-code4** [code4romania/vic#285]
### Description
I wanted to create a new user on VIC mobile. On the first step, I used phone number +40000000000 (an already used phone number). I was allowed to continue to the next step, even if the data was not valid. In the second step, I confirmed the email, and continued to next step. In the 3rd step, I filled in personal data information, and when trying to proceed to the next step, the error message "already used data" appeared. 

### Test environment
VIC mobile, iOS

### Preconditions
_None_

### Test Data
Use phone number +40000000000

### Steps of Reproduction
See screenshot / description.

### Expected Result
Ideally: 
In the first step of the registration process, user is prompted with the error message when trying to proceed to the second step, before being requested to enter the email code (to confirm email). 
Nice to have: If user inputted an email/phone number associated to a previously created account, user is redirected to login page with displayed text "Exista deja un cont creat utilizand acest email sau numar de telefon. Intra in cont" ([see Figma](https://www.figma.com/file/fBxQarllPrE9kEt22bIBa1/VIC-(Management-de-voluntari)-%2F-ex.-TEO?type=design&node-id=11064-6133&mode=design&t=fvXDn8zrEE9f5umc-4))

### Actual Result
Error message is shown late in the process, and user is allowed to continue the process in the first 3 steps. 
See screenshot.

### Notes (optional)
Related issues: #225 , #218 

### Screenshots (optional)

https://github.com/code4romania/vic/assets/95479576/d192cfbd-2be4-424b-9dcf-03eccf4e4003

**Comment by andrei-manda** [comment]
Closed -> duplicated by https://github.com/code4romania/vic/issues/232
