### ISSUE TITLE
Unable to Reset Filters On Volunteers lists

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#305]
**Preconditions:**
The user must be logged in on the "Voluntari activi" tab from "Lista voluntari" sub-page.

**Steps To Reproduce:**
1. Click on "Filtre" button
2. Filter the volunteer list using any of the available filters
3. Click on the "Resetează filtre" button.

**Expected Results:**
3. The filters are removed and the list displays all available data.

**Actual Results:**
3. The filters are **not** removed, and the volunteer list still displays data according to set filters.

**Comment by radulescuandrew** [comment]
@MarG66 @dragos1195 isn't this fixed? please mark the labels accordingly
