### ISSUE TITLE
Clearing the MultiSelect Does Not Restore the Correct Default State Resulting in Wrong Validation

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#309]
**Preconditions:**
The user must be logged in on the "Evenimente" page.

**Steps to Reproduce:**
1. Click on the "Adauga eveniment" button
2. Click on "Publica" button
3. Go to “Alege activitati”
4. Choose one item
5. Press clear (x button)
6. Click on the "Publica" button again

**Expected Results:**
6. Mandatory input error is displayed for the "Alege activitati" input.

**Actual Results:**
6. Mandatory input error is **NOT** displayed for the "Alege activitati" input.

**Development perspective:** 
5. Instead of null,  the value is now " [] ".

**Note:**
Can also be reproduced for "Target" -> "Selecteaza Departament" dropdown input.

**Comment by radulescuandrew** [comment]
@MarG66 Fix will be included in the `VIC FrontEnd Bump Version Fixes`
