### ISSUE TITLE
Bulk Small Bug 

### ISSUE THREAD

**Issue by andrei-manda** [code4romania/vic#318]
This issue will contain a list of small bugs, each detailed in a separate comment. This allows for all bugs to be addressed within a single pull request.

**Comment by andrei-manda** [comment]
Precondition:
- A contract with the 'Validare ONG' status must exist.

Steps of Reproduction:
1. [_Mobile_] Navigate to the 'Documente' page
2. [_Mobile_] Click the 'Vezi toate' button in the 'Propunere contract' section
3. [Web] Reject the contract
4. [_Mobile_] Click on the contract

![1](https://github.com/user-attachments/assets/ce6947ff-c049-46f1-a77e-eb3609605fb7)

**Comment by andrei-manda** [comment]
The application header overlaps with the phone's native header.

Environment:
- Android

**Note**:
- Introduced by #316 
- see ss: [link](https://private-user-images.githubusercontent.com/49789938/350949934-86a03a73-feb6-493b-8790-c77edc9b047d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDg0NTcsIm5iZiI6MTcyMTY0ODE1NywicGF0aCI6Ii80OTc4OTkzOC8zNTA5NDk5MzQtODZhMDNhNzMtZmViNi00OTNiLTg3OTAtYzc3ZWRjOWIwNDdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDExMzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTQwMTY5ZDM3Nzg2ZDZhOGUxZTg3ZGUyOTFkZjhmNTExNGFjNDAwYmI2ZmU5YjU2NDhiZTkzOGI1MzM4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mwRSC10si0FfcbBMZ9pD1BezK8tdK_YYKCcUwWtTYfI)

**Comment by andrei-manda** [comment]
**Description**:
When accessing the 'Date cont' page, the city list defaults to its initial option (_Selecteaza_) despite the user having specified a city during account creation. 
Additionally, by clicking on the input it does not open any list.

Notes:
This issue occurs intermittently, often after completing the profile to join an organization.

Environment:
- Android
- iOS

![4](https://github.com/user-attachments/assets/110a18ae-8dfe-48b7-8d8f-9a022e2147ea)

**Comment by andrei-manda** [comment]
**Description**:
Log in using the _marin@moongit.com_ account, navigate to the ''Ale organizatiilor mele' tab on the 'Evenimente' page, and attempt to join the 'Tribus Testing Race' event.

**Issue**:
- An error message from the attachment section is displayed, but it is not fully visible. 
- Additionally, if the volunteer navigates to the 'Voluntar' page, and the selected NGO is not the one with the event, it will be confusing; the volunteer may not realize they are viewing the wrong organization and will need to switch to the one with the event in order to complete their profile.

**Possible Solution**
- When the volunteer clicks the 'Particip' button, instead of showing an error message, display a modal that redirects the user to the 'Profil Voluntar' page for the respective NGO.

**Attachment**:
![5](https://github.com/user-attachments/assets/34ad7482-e700-4d96-a982-a192522fa8f5)

**Comment by MarG66** [comment]
**Issue**
A user can log into VIC directly using the URL when access to the app is restricted.

**Affected Areas:**
- Restricting NGO access to NGO Hub
- Restricting NGO access to the app
- Restricting NGO employee access to the app
- Directly accessing VIC with a fresh NGO account that has not added the app to it's HUB account

**Comment by MarG66** [comment]
[WEB-APP]
**Description:**
Dashboard graph does not fully display active volunteers line.

use account: dallas.braedan@milkcreeks.com
![image](https://github.com/user-attachments/assets/a0678a7f-51d2-4da5-8039-869e87d1b6f8)

**Comment by MarG66** [comment]
[Web-App]

Update "TEO" references to "VIC" for the "Descriere organizatie" section text on the "Structura ONG" page in view and edit modes.

![image](https://github.com/user-attachments/assets/1a8fde2d-a663-4098-849e-28a01510e779)

**Comment by luciatugui** [comment]
First 3 bugs are ready for testing.

**Comment by MarG66** [comment]
[Web-APP]
On the "Lista voluntari" sub-page, the search bar overlaps the reset filters button when the browser window is resized to 650 x 850.

Bug can be reproduced for all tabs on the "Lista voluntari" sub-page.

![image](https://github.com/user-attachments/assets/65b17d8b-209d-4094-a7a5-0cf71e49b2f6)

**Comment by MarG66** [comment]
[Web-App]
The calendar icon from an input can be seen when a dropdown is displayed on top of an input.

As seen on the "Fisa de activitate" side panel from "Ore de voluntariat" page. The calendar icon is part of another input (Data) and it can be seen through the "Eveniment" and "Activitate" dropdowns.
![image](https://github.com/user-attachments/assets/2e338199-7772-4788-90d4-bcdaa2c453b8)

**Comment by MarG66** [comment]
[Web-App]

**Issue**
When downloading a contract, the file name contains the contract id and name. Like: "b123a7b2-e401-4970-9319-987d2e9b925d-Contract_No.221.pdf"
The name should not have the contract id displayed.

**Suggestion:**
Replace the id with the volunteer name.

**Comment by luciatugui** [comment]
All tasks that are ready for testing are marked with 👍🏻.
Opened new issues:
- (https://github.com/code4romania/vic/issues/338) for https://github.com/code4romania/vic/issues/318#issuecomment-2252154505
- https://github.com/code4romania/onghub/issues/597 for https://github.com/code4romania/vic/issues/318#issuecomment-2244852540
