### ISSUE TITLE
Disclaimer Message Has No Use

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#337]
The disclaimer message "Dacă nu este selectat niciun departament, atunci 'Toată organizația' va fi selectată" displayed at the "Target" section of the event creating form has no use.

When selecting the "Selecteaza Departament" option, the user is forced to select a department because it is a mandatory input, thus making the disclaimer invalid.

See Rec
https://github.com/user-attachments/assets/d99469ad-15e1-40ef-88fb-4f81b78cc485

**Comment by radulescuandrew** [comment]
Invalid, as required.
