### ISSUE TITLE
[Contracts] Missing header row for the check mark column

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#409]
The check mark column from the first step of the contract generation form wizard is missing the header.
The check mark column should be of type radio as per design

See SS
![image](https://github.com/user-attachments/assets/c64e8213-ad59-46c8-8dd3-46de42945b88)

**Comment by radulescuandrew** [comment]
"The check mark column from the first step of the contract generation form wizard is missing the header." - is correct, only 1 can be selected. 

"The check mark column should be of type radio as per design" - the current table library does not support changing the button type. Need further investigation
