### ISSUE TITLE
[Contracts][Templates] Improper column sorting on tables

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#416]
**Issue:**
The sorting used for number and date columns is done as string thus the tables return data sorted incorectly.

For example, sorting ASC by the Contract Number, returns data in the following order:

 1
100
12
23
24
3

**Comment by radulescuandrew** [comment]
@MarG66 Actually is correct. The DocumentNumber is string and can be anything like `M1234`, `CNTR123`, etc. So we keep the sorting as string. Please close as invalid.
