### ISSUE TITLE
[Contracts] Unknown error is displayed when closing rejection confirmation bottom sheet

### ISSUE THREAD

**Issue by MarG66** [code4romania/vic#449]
**Preconditions:**
The user must be logged in on "Contract in asteptare" page;
The page must display a pending contract with "Semnare voluntar" status.

**Steps to Reproduce:**
1. Press on the pending contract
2. Press on the "Respinge Contract" button
3. Select a rejection reason from the "Motivul respingerii" input
4. Press on the "Trimite" button
5. Press outside the bottom sheet
6. Press on the "Trimite" button

**Expected Results:**
5. No action is taken or return the user to "Contract in asteptare" page.

**Actual Results**
5. The bottom sheet is closed
6. The "A aparut o eroare la respingerea contractului" error bottom sheet is displayed.

See Rec
https://github.com/user-attachments/assets/76d55377-cf90-411f-a247-ca2690012330

**Comment by luciatugui** [comment]
Now, after dismissing the modal, even if the user doesn't press on the "back to contracts" button, he will be redirected to the contracts page.
